### PR TITLE
move to Minishift and Maistra 0.10.0

### PR DESCRIPTION
**Pull request by Ladicek**

### CODE REVIEW

**Comment by sberyozkin** [comment]
@Ladicek so `istiooc` does not work any longer ? I've heard that it won't work for OpenShift 4, so may be the sooner we stop relying on it the better... Would be good though if Minishift istio add on shipped all of these files such as istio-operator, etc :-)

**Comment by juangon** [comment]
I checked using Fabric8 Maven plugin and works like a charm. Checking S2I approach now.

**Comment by Ladicek** [comment]
In my experience, getting `istiooc` running is a pain. I was able to make it work with Maistra 0.9.0, but the sidecar injector didn't work when I used `istiooc` from Maistra 0.10.0. Minishift, on the other hand, is pretty reliable.

There's a PR that updates the Minishift Istio addon to Maistra 0.10.0: https://github.com/minishift/minishift-addons/pull/184 However, it also directly installs Istio, in a different configuration than what we need. So I opted into installing the Istio operator ourselves, which is pretty easy actually. The only reason I added `istio-operator.yaml` here, instead of saying "use `oc apply -n istio-operator -f https://raw.githubusercontent.com/Maistra/istio-operator/maistra-0.10.0/deploy/maistra-operator.yaml`", is that the upstream YAML doesn't contain the `sysctl` hack for Elasticsearch. I don't want to instruct people to do `minishift ssh -- sysctl bla bla`. (Actually I probably should do that? It's just a single command...)

**Comment by sberyozkin** [comment]
@Ladicek sounds good, better have it under control with this example

**Review by sberyozkin — APPROVED** [review]

**Comment by brian-avery** [comment]
@Ladicek Just saw you referenced my Maistra 0.10 PR. Do you think it would be better to have the user create the controlplane.yaml themselves? Happy to update as such. I've been trying to open a PR for each Maistra release we do. Trying to find the balance between a 1 click "and you're up" to allow exploration of Istio and the flexibility for advanced users to use it as they wish.

**Comment by Ladicek** [comment]
@brian-avery It seems pull requests in the `minishift-addons` project are not properly reviewed, which is a shame :-/ And yes, I do think that there should be an addon that only installs the operator, and leaves the control plane deployment to the user. I'm not sure if that's how the `istio` addon should behave, or if it should be an extra addon for the advanced users.

**Pull request merged**
