### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by eye0fra**
Using default Jaeger query route

### CODE REVIEW

**Comment by Ladicek** [comment]
Hmm, did I really screw this up? I'll check :-)

**Review by Ladicek — APPROVED** [review]
Hmm, there are actually 2 routes to the Jaeger UI: `tracing` and `jaeger-query`. But the OpenShift web console shows `jaeger-query`, so I guess that one is somehow preferred...

**Comment by eye0fra** [comment]
Interesting, I didn't noticed there were 2.. and as well 2 services (tracing and jaeger-query) which apparently are identical.. wonder why.

**Comment by Ladicek** [comment]
Yea, same here :-)

**Pull request merged**
